from neo4j import GraphDatabase
import logging
from neo4j.exceptions import ServiceUnavailable

class LoadActors:

    def __init__(self, uri, user, password):
        self.driver = GraphDatabase.driver(uri, auth=(user, password))

    def close(self):
        self.driver.close()

    def create_actor(self, ptitle, proles, pperson, pborn):
        with self.driver.session() as session:
            # Write transactions allow the driver to handle retries and transient errors
            result = session.write_transaction(
                self._create_and_return_actors, ptitle, proles, pperson, pborn)
            for row in result:
                print("Created / merged person and label actor from Movie: " ,ptitle, "= {p}".format(p=row["p"]))


    @staticmethod
    def _create_and_return_actors(tx, title, roles, person, born):
        query = (
            "MERGE (p:Person:Actor { name: $name, born: $born})" 
            " RETURN p"
        )
        #print(query)

        result = tx.run(query, name=person, born=born, roles=roles)

        try:
            return [{"p": row["p"]["name"]} for row in result]
        except ServiceUnavailable as exception:
            logging.error("{query} raised an error: \n {exception}".format(
                query=query, exception=exception))
            raise

    def create_relationship(self, ptitle, proles, pperson, pborn):
        with self.driver.session() as session:
            # Write transactions allow the driver to handle retries and transient errors
            result = session.write_transaction(
                self._create_and_return_rel, ptitle, proles, pperson, pborn)
            for row in result:
                print("Created / merged relationship person and movie from: ", pperson, "through role : {r}".format(r=row["r"]))

    @staticmethod
    def _create_and_return_rel(tx, title, roles, person, born):
        query2 = (
            "MATCH (m:Movie) where m.title = $title  "
            "MATCH (p:Person:Actor {name: $name}) "
            "MERGE (p)-[r:ACTED_IN {roles: $roles}]->(m)" 
            " RETURN r"
        )

        #print (query)
        result = tx.run(query2, title=title, name=person, roles=roles)

        try:
            return [{"r": row["r"]["roles"]} for row in result]
        except ServiceUnavailable as exception:
            logging.error("{query} raised an error: \n {exception}".format(
                query=query, exception=exception))
            raise

if __name__ == "__main__":
    uri = "neo4j://3.83.97.78"
    user = "neo4j"
    password = "neo4j"
    app = LoadActors(uri, user, password)

    ######################################################################################################
    ## Create Person& Actors
    ######################################################################################################
    app.create_actor("Something's Gotta Give", "Julian Mercer", "Keanu Reeves",1970)
    app.create_actor("Johnny Mnemonic", "Johnny Mnemonic", "Keanu Reeves",1970)
    app.create_actor("The Replacements", "Shane Falco", "Keanu Reeves",1970)
    app.create_actor("The Devil's Advocate", "Kevin Lomax", "Keanu Reeves",1970)
    app.create_actor("The Matrix Revolutions", "Neo", "Keanu Reeves",1970)
    app.create_actor("The Matrix Reloaded", "Neo", "Keanu Reeves",1970)
    app.create_actor("The Matrix", "Neo", "Keanu Reeves",1970)
    app.create_actor("The Matrix Revolutions", "Trinity", "Carrie-Anne Moss",1970)
    app.create_actor("The Matrix Reloaded", "Trinity", "Carrie-Anne Moss",1970)
    app.create_actor("The Matrix", "Trinity", "Carrie-Anne Moss",1970)
    app.create_actor("The Matrix Revolutions", "Morpheus", "Laurence Fishburne",1970)
    app.create_actor("The Matrix Reloaded", "Morpheus", "Laurence Fishburne",1970)
    app.create_actor("The Matrix", "Morpheus", "Laurence Fishburne",1970)
    app.create_actor("V for Vendetta", "V", "Hugo Weaving",1970)
    app.create_actor("Cloud Atlas", "Bill Smoke;Haskell Moore;Tadeusz Kesselring;Nurse Noakes;Boardman Mephi;Old Georgie", "Hugo Weaving",1970)
    app.create_actor("The Matrix Revolutions", "Agent Smith", "Hugo Weaving",1970)
    app.create_actor("The Matrix Reloaded", "Agent Smith", "Hugo Weaving",1970)
    app.create_actor("The Matrix", "Agent Smith", "Hugo Weaving",1970)
    app.create_actor("The Matrix", "Emil", "Emil Eifrem",1970)
    app.create_actor("That Thing You Do", "Tina", "Charlize Theron",1970)
    app.create_actor("The Devil's Advocate", "Mary Ann Lomax", "Charlize Theron",1970)
    app.create_actor("The Devil's Advocate", "John Milton", "Al Pacino",1970)
    app.create_actor("Jerry Maguire", "Jerry Maguire", "Tom Cruise",1970)
    app.create_actor("Top Gun", "Maverick", "Tom Cruise",1970)
    app.create_actor("A Few Good Men", "Lt. Daniel Kaffee", "Tom Cruise",1970)
    app.create_actor("Something's Gotta Give", "Harry Sanborn", "Jack Nicholson",1970)
    app.create_actor("One Flew Over the Cuckoo's Nest", "Randle McMurphy", "Jack Nicholson",1970)
    app.create_actor("Hoffa", "Hoffa", "Jack Nicholson",1970)
    app.create_actor("As Good as It Gets", "Melvin Udall", "Jack Nicholson",1970)
    app.create_actor("A Few Good Men", "Col. Nathan R. Jessup", "Jack Nicholson",1970)
    app.create_actor("A Few Good Men", "Lt. Cdr. JoAnne Galloway", "Demi Moore",1970)
    app.create_actor("Apollo 13", "Jack Swigert", "Kevin Bacon",1970)
    app.create_actor("Frost/Nixon", "Jack Brennan", "Kevin Bacon",1970)
    app.create_actor("A Few Good Men", "Capt. Jack Ross", "Kevin Bacon",1970)
    app.create_actor("Stand By Me", "Ace Merrill", "Kiefer Sutherland",1970)
    app.create_actor("A Few Good Men", "Lt. Jonathan Kendrick", "Kiefer Sutherland",1970)
    app.create_actor("A Few Good Men", "Cpl. Jeffrey Barnes", "Noah Wyle",1970)
    app.create_actor("What Dreams May Come", "Albert Lewis", "Cuba Gooding Jr.",1970)
    app.create_actor("As Good as It Gets", "Frank Sachs", "Cuba Gooding Jr.",1970)
    app.create_actor("Jerry Maguire", "Rod Tidwell", "Cuba Gooding Jr.",1970)
    app.create_actor("A Few Good Men", "Cpl. Carl Hammaker", "Cuba Gooding Jr.",1970)
    app.create_actor("A Few Good Men", "Lt. Sam Weinberg", "Kevin Pollak",1970)
    app.create_actor("Hoffa", "Frank Fitzsimmons", "J.T. Walsh",1970)
    app.create_actor("A Few Good Men", "Lt. Col. Matthew Andrew Markinson", "J.T. Walsh",1970)
    app.create_actor("A Few Good Men", "Pfc. Louden Downey", "James Marshall",1970)
    app.create_actor("A Few Good Men", "Dr. Stone", "Christopher Guest",1970)
    app.create_actor("A Few Good Men", "Man in Bar", "Aaron Sorkin",1970)
    app.create_actor("Top Gun", "Charlie", "Kelly McGillis",1970)
    app.create_actor("Top Gun", "Iceman", "Val Kilmer",1970)
    app.create_actor("Top Gun", "Goose", "Anthony Edwards",1970)
    app.create_actor("Top Gun", "Viper", "Tom Skerritt",1970)
    app.create_actor("When Harry Met Sally", "Sally Albright", "Meg Ryan",1970)
    app.create_actor("Joe Versus the Volcano", "DeDe;Angelica Graynamore;Patricia Graynamore", "Meg Ryan",1970)
    app.create_actor("Sleepless in Seattle", "Annie Reed", "Meg Ryan",1970)
    app.create_actor("You've Got Mail", "Kathleen Kelly", "Meg Ryan",1970)
    app.create_actor("Top Gun", "Carole", "Meg Ryan",1970)
    app.create_actor("Jerry Maguire", "Dorothy Boyd", "Renee Zellweger",1970)
    app.create_actor("Jerry Maguire", "Avery Bishop", "Kelly Preston",1970)
    app.create_actor("Stand By Me", "Vern Tessio", "Jerry O'Connell",1970)
    app.create_actor("Jerry Maguire", "Frank Cushman", "Jerry O'Connell",1970)
    app.create_actor("Jerry Maguire", "Bob Sugar", "Jay Mohr",1970)
    app.create_actor("The Green Mile", "Jan Edgecomb", "Bonnie Hunt",1970)
    app.create_actor("Jerry Maguire", "Laurel Boyd", "Bonnie Hunt",1970)
    app.create_actor("Jerry Maguire", "Marcee Tidwell", "Regina King",1970)
    app.create_actor("Jerry Maguire", "Ray Boyd", "Jonathan Lipnicki",1970)
    app.create_actor("Stand By Me", "Chris Chambers", "River Phoenix",1970)
    app.create_actor("Stand By Me", "Teddy Duchamp", "Corey Feldman",1970)
    app.create_actor("Stand By Me", "Gordie Lachance", "Wil Wheaton",1970)
    app.create_actor("Stand By Me", "Denny Lachance", "John Cusack",1970)
    app.create_actor("RescueDawn", "Admiral", "Marshall Bell",1970)
    app.create_actor("Stand By Me", "Mr. Lachance", "Marshall Bell",1970)
    app.create_actor("Cast Away", "Kelly Frears", "Helen Hunt",1970)
    app.create_actor("Twister", "Dr. Jo Harding", "Helen Hunt",1970)
    app.create_actor("As Good as It Gets", "Carol Connelly", "Helen Hunt",1970)
    app.create_actor("You've Got Mail", "Frank Navasky", "Greg Kinnear",1970)
    app.create_actor("As Good as It Gets", "Simon Bishop", "Greg Kinnear",1970)
    app.create_actor("What Dreams May Come", "Simon Bishop", "Annabella Sciorra",1970)
    app.create_actor("Snow Falling on Cedars", "Nels Gudmundsson", "Max von Sydow",1970)
    app.create_actor("What Dreams May Come", "The Tracker", "Max von Sydow",1970)
    app.create_actor("What Dreams May Come", "The Face", "Werner Herzog",1970)
    app.create_actor("Bicentennial Man", "Andrew Marin", "Robin Williams",1970)
    app.create_actor("The Birdcage", "Armand Goldman", "Robin Williams",1970)
    app.create_actor("What Dreams May Come", "Chris Nielsen", "Robin Williams",1970)
    app.create_actor("Snow Falling on Cedars", "Ishmael Chambers", "Ethan Hawke",1970)
    app.create_actor("Ninja Assassin", "Takeshi", "Rick Yune",1970)
    app.create_actor("Snow Falling on Cedars", "Kazuo Miyamoto", "Rick Yune",1970)
    app.create_actor("The Green Mile", "Warden Hal Moores", "James Cromwell",1970)
    app.create_actor("Snow Falling on Cedars", "Judge Fielding", "James Cromwell",1970)
    app.create_actor("You've Got Mail", "Patricia Eden", "Parker Posey",1970)
    app.create_actor("You've Got Mail", "Kevin Jackson", "Dave Chappelle",1970)
    app.create_actor("RescueDawn", "Duane", "Steve Zahn",1970)
    app.create_actor("You've Got Mail", "George Pappas", "Steve Zahn",1970)
    app.create_actor("A League of Their Own", "Jimmy Dugan", "Tom Hanks",1970)
    app.create_actor("The Polar Express", "Hero Boy;Father;Conductor;Hobo;Scrooge;Santa Claus", "Tom Hanks",1970)
    app.create_actor("Charlie Wilson's War", "Rep. Charlie Wilson", "Tom Hanks",1970)
    app.create_actor("Cast Away", "Chuck Noland", "Tom Hanks",1970)
    app.create_actor("Apollo 13", "Jim Lovell", "Tom Hanks",1970)
    app.create_actor("The Green Mile", "Paul Edgecomb", "Tom Hanks",1970)
    app.create_actor("The Da Vinci Code", "Dr. Robert Langdon", "Tom Hanks",1970)
    app.create_actor("Cloud Atlas", "Zachry;Dr. Henry Goose;Isaac Sachs;Dermot Hoggins", "Tom Hanks",1970)
    app.create_actor("That Thing You Do", "Mr. White", "Tom Hanks",1970)
    app.create_actor("Joe Versus the Volcano", "Joe Banks", "Tom Hanks",1970)
    app.create_actor("Sleepless in Seattle", "Sam Baldwin", "Tom Hanks",1970)
    app.create_actor("You've Got Mail", "Joe Fox", "Tom Hanks",1970)
    app.create_actor("Sleepless in Seattle", "Suzy", "Rita Wilson",1970)
    app.create_actor("Sleepless in Seattle", "Walter", "Bill Pullman",1970)
    app.create_actor("Sleepless in Seattle", "Greg", "Victor Garber",1970)
    app.create_actor("A League of Their Own", "Doris Murphy", "Rosie O'Donnell",1970)
    app.create_actor("Sleepless in Seattle", "Becky", "Rosie O'Donnell",1970)
    app.create_actor("The Birdcage", "Albert Goldman", "Nathan Lane",1970)
    app.create_actor("Joe Versus the Volcano", "Baw", "Nathan Lane",1970)
    app.create_actor("When Harry Met Sally", "Harry Burns", "Billy Crystal",1970)
    app.create_actor("When Harry Met Sally", "Marie", "Carrie Fisher",1970)
    app.create_actor("When Harry Met Sally", "Jess", "Bruno Kirby",1970)
    app.create_actor("That Thing You Do", "Faye Dolan", "Liv Tyler",1970)
    app.create_actor("The Replacements", "Annabelle Farrell", "Brooke Langton",1970)
    app.create_actor("Unforgiven", "Little Bill Daggett", "Gene Hackman",1970)
    app.create_actor("The Birdcage", "Sen. Kevin Keeley", "Gene Hackman",1970)
    app.create_actor("The Replacements", "Jimmy McGinty", "Gene Hackman",1970)
    app.create_actor("The Replacements", "Clifford Franklin", "Orlando Jones",1970)
    app.create_actor("RescueDawn", "Dieter Dengler", "Christian Bale",1970)
    app.create_actor("Twister", "Eddie", "Zach Grenier",1970)
    app.create_actor("RescueDawn", "Squad Leader", "Zach Grenier",1970)
    app.create_actor("Unforgiven", "English Bob", "Richard Harris",1970)
    app.create_actor("Unforgiven", "Bill Munny", "Clint Eastwood",1970)
    app.create_actor("Johnny Mnemonic", "Takahashi", "Takeshi Kitano",1970)
    app.create_actor("Johnny Mnemonic", "Jane", "Dina Meyer",1970)
    app.create_actor("Johnny Mnemonic", "J-Bone", "Ice-T",1970)
    app.create_actor("Cloud Atlas", "Luisa Rey;Jocasta Ayrs;Ovid;Meronym", "Halle Berry",1970)
    app.create_actor("Cloud Atlas", "Vyvyan Ayrs;Captain Molyneux;Timothy Cavendish", "Jim Broadbent",1970)
    app.create_actor("The Da Vinci Code", "Sir Leight Teabing", "Ian McKellen",1970)
    app.create_actor("The Da Vinci Code", "Sophie Neveu", "Audrey Tautou",1970)
    app.create_actor("The Da Vinci Code", "Silas", "Paul Bettany",1970)
    app.create_actor("V for Vendetta", "Evey Hammond", "Natalie Portman",1970)
    app.create_actor("V for Vendetta", "Eric Finch", "Stephen Rea",1970)
    app.create_actor("V for Vendetta", "High Chancellor Adam Sutler", "John Hurt",1970)
    app.create_actor("Ninja Assassin", "Ryan Maslow", "Ben Miles",1970)
    app.create_actor("Speed Racer", "Cass Jones", "Ben Miles",1970)
    app.create_actor("V for Vendetta", "Dascomb", "Ben Miles",1970)
    app.create_actor("Speed Racer", "Speed Racer", "Emile Hirsch",1970)
    app.create_actor("Speed Racer", "Pops", "John Goodman",1970)
    app.create_actor("Speed Racer", "Mom", "Susan Sarandon",1970)
    app.create_actor("Speed Racer", "Racer X", "Matthew Fox",1970)
    app.create_actor("Speed Racer", "Trixie", "Christina Ricci",1970)
    app.create_actor("Ninja Assassin", "Raizo", "Rain",1970)
    app.create_actor("Speed Racer", "Taejo Togokahn", "Rain",1970)
    app.create_actor("Ninja Assassin", "Mika Coretti", "Naomie Harris",1970)
    app.create_actor("The Green Mile", "John Coffey", "Michael Clarke Duncan",1970)
    app.create_actor("The Green Mile", "Brutus 'Brutal' Howell", "David Morse",1970)
    app.create_actor("Frost/Nixon", "James Reston, Jr.", "Sam Rockwell",1970)
    app.create_actor("The Green Mile", "Wild Bill' Wharton", "Sam Rockwell",1970)
    app.create_actor("Apollo 13", "Ken Mattingly", "Gary Sinise",1970)
    app.create_actor("The Green Mile", "Burt Hammersmith", "Gary Sinise",1970)
    app.create_actor("The Green Mile", "Melinda Moores", "Patricia Clarkson",1970)
    app.create_actor("Frost/Nixon", "Richard Nixon", "Frank Langella",1970)
    app.create_actor("Frost/Nixon", "David Frost", "Michael Sheen",1970)
    app.create_actor("Bicentennial Man", "Rupert Burns", "Oliver Platt",1970)
    app.create_actor("Frost/Nixon", "Bob Zelnick", "Oliver Platt",1970)
    app.create_actor("One Flew Over the Cuckoo's Nest", "Martini", "Danny DeVito",1970)
    app.create_actor("Hoffa", "Robert 'Bobby' Ciaro", "Danny DeVito",1970)
    app.create_actor("Hoffa", "Peter 'Pete' Connelly", "John C. Reilly",1970)
    app.create_actor("Apollo 13", "Gene Kranz", "Ed Harris",1970)
    app.create_actor("A League of Their Own", "Bob Hinson", "Bill Paxton",1970)
    app.create_actor("Twister", "Bill Harding", "Bill Paxton",1970)
    app.create_actor("Apollo 13", "Fred Haise", "Bill Paxton",1970)
    app.create_actor("Charlie Wilson's War", "Gust Avrakotos", "Philip Seymour Hoffman",1970)
    app.create_actor("Twister", "Dustin 'Dusty' Davis", "Philip Seymour Hoffman",1970)
    app.create_actor("Something's Gotta Give", "Erica Barry", "Diane Keaton",1970)
    app.create_actor("Charlie Wilson's War", "Joanne Herring", "Julia Roberts",1970)
    app.create_actor("A League of Their Own", "All the Way' Mae Mordabito", "Madonna",1970)
    app.create_actor("A League of Their Own", "Dottie Hinson", "Geena Davis",1970)
    app.create_actor("A League of Their Own", "Kit Keller", "Lori Petty",1970)
    
    ######################################################################################################
    ## Create Relationship between Person & Movie through ACTED_IN
    ######################################################################################################
    app.create_relationship("Something's Gotta Give", "Julian Mercer", "Keanu Reeves",1970)
    app.create_relationship("Johnny Mnemonic", "Johnny Mnemonic", "Keanu Reeves",1970)
    app.create_relationship("The Replacements", "Shane Falco", "Keanu Reeves",1970)
    app.create_relationship("The Devil's Advocate", "Kevin Lomax", "Keanu Reeves",1970)
    app.create_relationship("The Matrix Revolutions", "Neo", "Keanu Reeves",1970)
    app.create_relationship("The Matrix Reloaded", "Neo", "Keanu Reeves",1970)
    app.create_relationship("The Matrix", "Neo", "Keanu Reeves",1970)
    app.create_relationship("The Matrix Revolutions", "Trinity", "Carrie-Anne Moss",1970)
    app.create_relationship("The Matrix Reloaded", "Trinity", "Carrie-Anne Moss",1970)
    app.create_relationship("The Matrix", "Trinity", "Carrie-Anne Moss",1970)
    app.create_relationship("The Matrix Revolutions", "Morpheus", "Laurence Fishburne",1970)
    app.create_relationship("The Matrix Reloaded", "Morpheus", "Laurence Fishburne",1970)
    app.create_relationship("The Matrix", "Morpheus", "Laurence Fishburne",1970)
    app.create_relationship("V for Vendetta", "V", "Hugo Weaving",1970)
    app.create_relationship("Cloud Atlas", "Bill Smoke;Haskell Moore;Tadeusz Kesselring;Nurse Noakes;Boardman Mephi;Old Georgie", "Hugo Weaving",1970)
    app.create_relationship("The Matrix Revolutions", "Agent Smith", "Hugo Weaving",1970)
    app.create_relationship("The Matrix Reloaded", "Agent Smith", "Hugo Weaving",1970)
    app.create_relationship("The Matrix", "Agent Smith", "Hugo Weaving",1970)
    app.create_relationship("The Matrix", "Emil", "Emil Eifrem",1970)
    app.create_relationship("That Thing You Do", "Tina", "Charlize Theron",1970)
    app.create_relationship("The Devil's Advocate", "Mary Ann Lomax", "Charlize Theron",1970)
    app.create_relationship("The Devil's Advocate", "John Milton", "Al Pacino",1970)
    app.create_relationship("Jerry Maguire", "Jerry Maguire", "Tom Cruise",1970)
    app.create_relationship("Top Gun", "Maverick", "Tom Cruise",1970)
    app.create_relationship("A Few Good Men", "Lt. Daniel Kaffee", "Tom Cruise",1970)
    app.create_relationship("Something's Gotta Give", "Harry Sanborn", "Jack Nicholson",1970)
    app.create_relationship("One Flew Over the Cuckoo's Nest", "Randle McMurphy", "Jack Nicholson",1970)
    app.create_relationship("Hoffa", "Hoffa", "Jack Nicholson",1970)
    app.create_relationship("As Good as It Gets", "Melvin Udall", "Jack Nicholson",1970)
    app.create_relationship("A Few Good Men", "Col. Nathan R. Jessup", "Jack Nicholson",1970)
    app.create_relationship("A Few Good Men", "Lt. Cdr. JoAnne Galloway", "Demi Moore",1970)
    app.create_relationship("Apollo 13", "Jack Swigert", "Kevin Bacon",1970)
    app.create_relationship("Frost/Nixon", "Jack Brennan", "Kevin Bacon",1970)
    app.create_relationship("A Few Good Men", "Capt. Jack Ross", "Kevin Bacon",1970)
    app.create_relationship("Stand By Me", "Ace Merrill", "Kiefer Sutherland",1970)
    app.create_relationship("A Few Good Men", "Lt. Jonathan Kendrick", "Kiefer Sutherland",1970)
    app.create_relationship("A Few Good Men", "Cpl. Jeffrey Barnes", "Noah Wyle",1970)
    app.create_relationship("What Dreams May Come", "Albert Lewis", "Cuba Gooding Jr.",1970)
    app.create_relationship("As Good as It Gets", "Frank Sachs", "Cuba Gooding Jr.",1970)
    app.create_relationship("Jerry Maguire", "Rod Tidwell", "Cuba Gooding Jr.",1970)
    app.create_relationship("A Few Good Men", "Cpl. Carl Hammaker", "Cuba Gooding Jr.",1970)
    app.create_relationship("A Few Good Men", "Lt. Sam Weinberg", "Kevin Pollak",1970)
    app.create_relationship("Hoffa", "Frank Fitzsimmons", "J.T. Walsh",1970)
    app.create_relationship("A Few Good Men", "Lt. Col. Matthew Andrew Markinson", "J.T. Walsh",1970)
    app.create_relationship("A Few Good Men", "Pfc. Louden Downey", "James Marshall",1970)
    app.create_relationship("A Few Good Men", "Dr. Stone", "Christopher Guest",1970)
    app.create_relationship("A Few Good Men", "Man in Bar", "Aaron Sorkin",1970)
    app.create_relationship("Top Gun", "Charlie", "Kelly McGillis",1970)
    app.create_relationship("Top Gun", "Iceman", "Val Kilmer",1970)
    app.create_relationship("Top Gun", "Goose", "Anthony Edwards",1970)
    app.create_relationship("Top Gun", "Viper", "Tom Skerritt",1970)
    app.create_relationship("When Harry Met Sally", "Sally Albright", "Meg Ryan",1970)
    app.create_relationship("Joe Versus the Volcano", "DeDe;Angelica Graynamore;Patricia Graynamore", "Meg Ryan",1970)
    app.create_relationship("Sleepless in Seattle", "Annie Reed", "Meg Ryan",1970)
    app.create_relationship("You've Got Mail", "Kathleen Kelly", "Meg Ryan",1970)
    app.create_relationship("Top Gun", "Carole", "Meg Ryan",1970)
    app.create_relationship("Jerry Maguire", "Dorothy Boyd", "Renee Zellweger",1970)
    app.create_relationship("Jerry Maguire", "Avery Bishop", "Kelly Preston",1970)
    app.create_relationship("Stand By Me", "Vern Tessio", "Jerry O'Connell",1970)
    app.create_relationship("Jerry Maguire", "Frank Cushman", "Jerry O'Connell",1970)
    app.create_relationship("Jerry Maguire", "Bob Sugar", "Jay Mohr",1970)
    app.create_relationship("The Green Mile", "Jan Edgecomb", "Bonnie Hunt",1970)
    app.create_relationship("Jerry Maguire", "Laurel Boyd", "Bonnie Hunt",1970)
    app.create_relationship("Jerry Maguire", "Marcee Tidwell", "Regina King",1970)
    app.create_relationship("Jerry Maguire", "Ray Boyd", "Jonathan Lipnicki",1970)
    app.create_relationship("Stand By Me", "Chris Chambers", "River Phoenix",1970)
    app.create_relationship("Stand By Me", "Teddy Duchamp", "Corey Feldman",1970)
    app.create_relationship("Stand By Me", "Gordie Lachance", "Wil Wheaton",1970)
    app.create_relationship("Stand By Me", "Denny Lachance", "John Cusack",1970)
    app.create_relationship("RescueDawn", "Admiral", "Marshall Bell",1970)
    app.create_relationship("Stand By Me", "Mr. Lachance", "Marshall Bell",1970)
    app.create_relationship("Cast Away", "Kelly Frears", "Helen Hunt",1970)
    app.create_relationship("Twister", "Dr. Jo Harding", "Helen Hunt",1970)
    app.create_relationship("As Good as It Gets", "Carol Connelly", "Helen Hunt",1970)
    app.create_relationship("You've Got Mail", "Frank Navasky", "Greg Kinnear",1970)
    app.create_relationship("As Good as It Gets", "Simon Bishop", "Greg Kinnear",1970)
    app.create_relationship("What Dreams May Come", "Simon Bishop", "Annabella Sciorra",1970)
    app.create_relationship("Snow Falling on Cedars", "Nels Gudmundsson", "Max von Sydow",1970)
    app.create_relationship("What Dreams May Come", "The Tracker", "Max von Sydow",1970)
    app.create_relationship("What Dreams May Come", "The Face", "Werner Herzog",1970)
    app.create_relationship("Bicentennial Man", "Andrew Marin", "Robin Williams",1970)
    app.create_relationship("The Birdcage", "Armand Goldman", "Robin Williams",1970)
    app.create_relationship("What Dreams May Come", "Chris Nielsen", "Robin Williams",1970)
    app.create_relationship("Snow Falling on Cedars", "Ishmael Chambers", "Ethan Hawke",1970)
    app.create_relationship("Ninja Assassin", "Takeshi", "Rick Yune",1970)
    app.create_relationship("Snow Falling on Cedars", "Kazuo Miyamoto", "Rick Yune",1970)
    app.create_relationship("The Green Mile", "Warden Hal Moores", "James Cromwell",1970)
    app.create_relationship("Snow Falling on Cedars", "Judge Fielding", "James Cromwell",1970)
    app.create_relationship("You've Got Mail", "Patricia Eden", "Parker Posey",1970)
    app.create_relationship("You've Got Mail", "Kevin Jackson", "Dave Chappelle",1970)
    app.create_relationship("RescueDawn", "Duane", "Steve Zahn",1970)
    app.create_relationship("You've Got Mail", "George Pappas", "Steve Zahn",1970)
    app.create_relationship("A League of Their Own", "Jimmy Dugan", "Tom Hanks",1970)
    app.create_relationship("The Polar Express", "Hero Boy;Father;Conductor;Hobo;Scrooge;Santa Claus", "Tom Hanks",1970)
    app.create_relationship("Charlie Wilson's War", "Rep. Charlie Wilson", "Tom Hanks",1970)
    app.create_relationship("Cast Away", "Chuck Noland", "Tom Hanks",1970)
    app.create_relationship("Apollo 13", "Jim Lovell", "Tom Hanks",1970)
    app.create_relationship("The Green Mile", "Paul Edgecomb", "Tom Hanks",1970)
    app.create_relationship("The Da Vinci Code", "Dr. Robert Langdon", "Tom Hanks",1970)
    app.create_relationship("Cloud Atlas", "Zachry;Dr. Henry Goose;Isaac Sachs;Dermot Hoggins", "Tom Hanks",1970)
    app.create_relationship("That Thing You Do", "Mr. White", "Tom Hanks",1970)
    app.create_relationship("Joe Versus the Volcano", "Joe Banks", "Tom Hanks",1970)
    app.create_relationship("Sleepless in Seattle", "Sam Baldwin", "Tom Hanks",1970)
    app.create_relationship("You've Got Mail", "Joe Fox", "Tom Hanks",1970)
    app.create_relationship("Sleepless in Seattle", "Suzy", "Rita Wilson",1970)
    app.create_relationship("Sleepless in Seattle", "Walter", "Bill Pullman",1970)
    app.create_relationship("Sleepless in Seattle", "Greg", "Victor Garber",1970)
    app.create_relationship("A League of Their Own", "Doris Murphy", "Rosie O'Donnell",1970)
    app.create_relationship("Sleepless in Seattle", "Becky", "Rosie O'Donnell",1970)
    app.create_relationship("The Birdcage", "Albert Goldman", "Nathan Lane",1970)
    app.create_relationship("Joe Versus the Volcano", "Baw", "Nathan Lane",1970)
    app.create_relationship("When Harry Met Sally", "Harry Burns", "Billy Crystal",1970)
    app.create_relationship("When Harry Met Sally", "Marie", "Carrie Fisher",1970)
    app.create_relationship("When Harry Met Sally", "Jess", "Bruno Kirby",1970)
    app.create_relationship("That Thing You Do", "Faye Dolan", "Liv Tyler",1970)
    app.create_relationship("The Replacements", "Annabelle Farrell", "Brooke Langton",1970)
    app.create_relationship("Unforgiven", "Little Bill Daggett", "Gene Hackman",1970)
    app.create_relationship("The Birdcage", "Sen. Kevin Keeley", "Gene Hackman",1970)
    app.create_relationship("The Replacements", "Jimmy McGinty", "Gene Hackman",1970)
    app.create_relationship("The Replacements", "Clifford Franklin", "Orlando Jones",1970)
    app.create_relationship("RescueDawn", "Dieter Dengler", "Christian Bale",1970)
    app.create_relationship("Twister", "Eddie", "Zach Grenier",1970)
    app.create_relationship("RescueDawn", "Squad Leader", "Zach Grenier",1970)
    app.create_relationship("Unforgiven", "English Bob", "Richard Harris",1970)
    app.create_relationship("Unforgiven", "Bill Munny", "Clint Eastwood",1970)
    app.create_relationship("Johnny Mnemonic", "Takahashi", "Takeshi Kitano",1970)
    app.create_relationship("Johnny Mnemonic", "Jane", "Dina Meyer",1970)
    app.create_relationship("Johnny Mnemonic", "J-Bone", "Ice-T",1970)
    app.create_relationship("Cloud Atlas", "Luisa Rey;Jocasta Ayrs;Ovid;Meronym", "Halle Berry",1970)
    app.create_relationship("Cloud Atlas", "Vyvyan Ayrs;Captain Molyneux;Timothy Cavendish", "Jim Broadbent",1970)
    app.create_relationship("The Da Vinci Code", "Sir Leight Teabing", "Ian McKellen",1970)
    app.create_relationship("The Da Vinci Code", "Sophie Neveu", "Audrey Tautou",1970)
    app.create_relationship("The Da Vinci Code", "Silas", "Paul Bettany",1970)
    app.create_relationship("V for Vendetta", "Evey Hammond", "Natalie Portman",1970)
    app.create_relationship("V for Vendetta", "Eric Finch", "Stephen Rea",1970)
    app.create_relationship("V for Vendetta", "High Chancellor Adam Sutler", "John Hurt",1970)
    app.create_relationship("Ninja Assassin", "Ryan Maslow", "Ben Miles",1970)
    app.create_relationship("Speed Racer", "Cass Jones", "Ben Miles",1970)
    app.create_relationship("V for Vendetta", "Dascomb", "Ben Miles",1970)
    app.create_relationship("Speed Racer", "Speed Racer", "Emile Hirsch",1970)
    app.create_relationship("Speed Racer", "Pops", "John Goodman",1970)
    app.create_relationship("Speed Racer", "Mom", "Susan Sarandon",1970)
    app.create_relationship("Speed Racer", "Racer X", "Matthew Fox",1970)
    app.create_relationship("Speed Racer", "Trixie", "Christina Ricci",1970)
    app.create_relationship("Ninja Assassin", "Raizo", "Rain",1970)
    app.create_relationship("Speed Racer", "Taejo Togokahn", "Rain",1970)
    app.create_relationship("Ninja Assassin", "Mika Coretti", "Naomie Harris",1970)
    app.create_relationship("The Green Mile", "John Coffey", "Michael Clarke Duncan",1970)
    app.create_relationship("The Green Mile", "Brutus 'Brutal' Howell", "David Morse",1970)
    app.create_relationship("Frost/Nixon", "James Reston, Jr.", "Sam Rockwell",1970)
    app.create_relationship("The Green Mile", "Wild Bill' Wharton", "Sam Rockwell",1970)
    app.create_relationship("Apollo 13", "Ken Mattingly", "Gary Sinise",1970)
    app.create_relationship("The Green Mile", "Burt Hammersmith", "Gary Sinise",1970)
    app.create_relationship("The Green Mile", "Melinda Moores", "Patricia Clarkson",1970)
    app.create_relationship("Frost/Nixon", "Richard Nixon", "Frank Langella",1970)
    app.create_relationship("Frost/Nixon", "David Frost", "Michael Sheen",1970)
    app.create_relationship("Bicentennial Man", "Rupert Burns", "Oliver Platt",1970)
    app.create_relationship("Frost/Nixon", "Bob Zelnick", "Oliver Platt",1970)
    app.create_relationship("One Flew Over the Cuckoo's Nest", "Martini", "Danny DeVito",1970)
    app.create_relationship("Hoffa", "Robert 'Bobby' Ciaro", "Danny DeVito",1970)
    app.create_relationship("Hoffa", "Peter 'Pete' Connelly", "John C. Reilly",1970)
    app.create_relationship("Apollo 13", "Gene Kranz", "Ed Harris",1970)
    app.create_relationship("A League of Their Own", "Bob Hinson", "Bill Paxton",1970)
    app.create_relationship("Twister", "Bill Harding", "Bill Paxton",1970)
    app.create_relationship("Apollo 13", "Fred Haise", "Bill Paxton",1970)
    app.create_relationship("Charlie Wilson's War", "Gust Avrakotos", "Philip Seymour Hoffman",1970)
    app.create_relationship("Twister", "Dustin 'Dusty' Davis", "Philip Seymour Hoffman",1970)
    app.create_relationship("Something's Gotta Give", "Erica Barry", "Diane Keaton",1970)
    app.create_relationship("Charlie Wilson's War", "Joanne Herring", "Julia Roberts",1970)
    app.create_relationship("A League of Their Own", "All the Way' Mae Mordabito", "Madonna",1970)
    app.create_relationship("A League of Their Own", "Dottie Hinson", "Geena Davis",1970)
    app.create_relationship("A League of Their Own", "Kit Keller", "Lori Petty",1970)

    app.close()
